config/routes.rb
Rails.application.routes.draw do
  root to: 'hotels#index'
    resources :hotels, only: [ :create, :index, :show, :new ] do
      resources :apparels, only: [ :new, :create ]
  end
  resources :apparels, only: [ :destroy, :edit, :update ]
end

app/models/apparel.rb
class Apparel < ApplicationRecord
  belongs_to :hotel

  CATEGORIES = ['Jeans', 'Jacket', 'Shirt', 'Sweatshirt', 'Pants', 'Room Wear']

  validates :brand, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES }
  validates :photo, presence: true

  has_one_attached :photo
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :apparels

  validates :name, presence: true, uniqueness: true
  validates :address, presence: true, uniqueness: true

  has_one_attached :photo
end

app/controllers/apparels_controller.rb
class ApparelsController < ApplicationController
  def new
    @hotel = Hotel.find(params[:hotel_id])
    @apparel = Apparel.new
  end

  def create
    @apparel = Apparel.new(apparel_params)
    @hotel = Hotel.find(params[:hotel_id])
    @apparel.hotel = @hotel
    if @apparel.save
      redirect_to hotel_path(@hotel)
    else
      render :new
    end
  end

  def edit
    @apparel = Apparel.find(params[:id])
  end

  def update
    @apparel = Apparel.find(params[:id])
    if @apparel.update(apparel_params)
      redirect_to hotel_path(@apparel.hotel)
    else
      render :edit
    end
  end

  def destroy
    @apparel = Apparel.find(params[:id])
    @apparel.destroy
    redirect_to hotel_path(@apparel.hotel)
  end

  private

  def apparel_params
    params.require(:apparel).permit(:brand, :category, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def index
    @hotels = Hotel.all
    @search = params["search"]
    if @search.present?
      @query = @search["name"]
      @hotels = Hotel.where("name ILIKE ?", "%#{@query}%")
    end
  end

  def show
    @hotel = Hotel.find(params[:id])
  end

  def new
    @hotel = Hotel.new
  end

  def create
    @hotel = Hotel.new(hotel_params)
    if @hotel.save
      redirect_to hotel_path(@hotel)
    else
      render :new
    end
  end

  private

  def hotel_params
    params.require(:hotel).permit(:name, :address, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apparels/edit.html.erb
<div class="page">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1490481651871-ab68de25d43d?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80);">
    <div class="container">
      <h1>Yaddo provides <strong>fashionable</strong> clothes for your special stay</h1>
      <p>Clothes sharing for less waste and cleaner environment</p>
    </div>
  </div>
    <div class="title-new">
    <h1>Edit Clothes</h1>
  </div>
  <div class="simple-form">
    <%= simple_form_for @apparel do |f| %>
      <%= f.input :brand %>
      <%= f.input :category, collection: Apparel::CATEGORIES, include_blank: false %>
      <%= f.input :photo, as: :file %>
      <div class="button-div">
        <%= f.submit 'Update', class: "btn btn-ghost" %>
      </div>
    <% end %>
  </div>
</div>

app/views/apparels/new.html.erb
<div class="page">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1490481651871-ab68de25d43d?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80);">
    <div class="container">
      <h1>Yaddo provides <strong>fashionable</strong> clothes for your special stay</h1>
      <p>Clothes sharing for less waste and cleaner environment</p>
    </div>
  </div>
  <div class="title-new">
    <h1>Add Clothes</h1>
  </div>
  <div class="simple-form">
    <%= simple_form_for [@hotel, @apparel] do |f| %>
      <%= f.input :brand %>
      <%= f.input :category, collection: Apparel::CATEGORIES, include_blank: false %>
      <%= f.input :photo, as: :file %>
      <div class="button-div">
        <%= f.submit 'Add', class: "btn btn-ghost" %>
      </div>
    <% end %>
  </div>
</div>

app/views/hotels/draft.html.erb
    <%= simple_form_for :search, url: root_path, method: :get, html: { class: 'form-inline' } do |f| %>
      <div class="search-form-control form-group">
      <%= f.input :name, intput_html: {value: ""} %>
            <%= f.submit "Search", class: "btn btn-flat"%>
            <% end %>

app/views/hotels/index.html.erb
<div class="page">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1490481651871-ab68de25d43d?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80);">
    <div class="container">
      <h1>Yaddo provides <strong>fashionable</strong> clothes for your special stay</h1>
      <p>Clothes sharing for less waste and cleaner environment</p>
    </div>
    <%= simple_form_for :search, url: root_path, method: :get do |f| %>
      <div class="search-form-control form-group">
        <input class="form-control string required" type="text" name="query" id="search_query" placeholder="doesn't work but would be cool if it did">
        <button name="button" type="submit" class="btn btn-flat">
          <i class="fas fa-search"></i>  Search
        </button>
      </div>
    <% end %>
  </div>
  <div class="index-title">
    <span style="background-color: #C07FD6">
      <h1>Participating Hotels</h1>
  </div>
  <div class="cards">
    <% @hotels.each do |hotel| %>
      <div class="card-trip">
        <% if hotel.photo.attached? %>
          <img src="<%= cl_image_path hotel.photo.key, crop: :fill %>">
        <% else %>
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
        <% end %>
        <div class="card-trip-infos">
          <div>
            <h2><%= hotel.name %></h2>
            <p><%= hotel.address %></p>
          </div>
          <div class="card-trip-pricing">
            <%= link_to "View Clothes", hotel_path(hotel), class: "btn btn-flat" %>
            <%# <h2 class="card-trip-pricing">See Clothes</h2> %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/hotels/new.html.erb
<div class="page">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1490481651871-ab68de25d43d?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80);">
    <div class="container">
      <h1>Yaddo provides <strong>fashionable</strong> clothes for your special stay</h1>
      <p>Clothes sharing for less waste and cleaner environment</p>
    </div>
  </div>
  <div class="title-new">
    <h1>Add a Hotel</h1>
  </div>
  <div class="simple-form">
    <%= simple_form_for @hotel do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :photo, as: :file %>
      <div class="button-div">
        <%= f.submit 'Add Hotel', class: "btn btn-ghost" %>
      </div>
    <% end %>
  </div>
</div>

app/views/hotels/show.html.erb
<div class="page">
  <div class="banner-photo">
    <% if @hotel.photo.attached? %>
      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @hotel.photo.key, height: 300, width: 400, resize: :limit %>);">
      <% else %>
        <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1517840901100-8179e982acb7?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80)">
        <% end %>
        <div class="container">
          <h1><%= @hotel.name %></h1>
          <p>  <%= @hotel.address %></p>
        </div>
      </div>
    </div>
    <div class="show-title">
      <h1>List of Clothes</h1>
      <div class="banner-button-container">
        <div class="banner-button">
          <%= link_to "Add Clothes", new_hotel_apparel_path(@hotel), class: "btn btn-ghost" %>
        </div>
      </div>
    </div>
    <div class="apparel-cards">
      <% @hotel.apparels.each do |apparel| %>
        <div class="card-trip">
        <% if apparel.photo.attached?%>
                  <img src="<%= cl_image_path apparel.photo.key, height: 300, width: 400, resize: :scale %>" />
    <% else %>
      <img src="https://res.cloudinary.com/dqnfjaom7/image/upload/v1613913278/uniqlo_shirt_vtejc5.jpg" />
    <% end %>
    <div class="card-trip-infos">
      <h2><%= apparel.brand %></h2>
      <p><%= apparel.category %></p>
      <div class="edit">
<%= link_to edit_apparel_path(apparel), class: 'card-edit-link' do %>
          <i class="far fa-edit"></i>
          <% end %>
      </div>
      <div class="delete">
        <%= link_to apparel_path(apparel), method: :delete, class: 'card-remove-link', data: { confirm: "Are you sure you want to delete?" } do %>
          <i class="far fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
</div>
</div>
<%# redirect_to hotel_path(@apparel.hotel) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yaddo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <%= link_to "#", class: "navbar-brand" do %>
        <%= image_tag "https://res.cloudinary.com/dqnfjaom7/image/upload/v1613908878/yaddo%E3%83%AD%E3%82%B3%E3%82%99_ffgdkr.png" %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Home", hotels_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add Hotel", new_hotel_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
    <%= yield %>
    <div class="footer">
      <div class="footer-links">
        <a href="https://www.instagram.com/yourapparel.2020/?igshid=1uwp0pigz1kgq" target="_blank"><i class="fab fa-instagram"></i></a>
        <a href="https://twitter.com/yourapparel2020?lang=en" target="_blank"><i class="fab fa-twitter"></i></a>
      </div>
      <div class="footer-copyright">
        Your Apparel 2020
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>